#!/bin/bash

curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh
cp vimrc.local ~/.vimrc.local
cp vimrc.bundles.local ~/.vimrc.bundles.local
cp vimrc.before.local ~/.vimrc.before.local

vim +BundleInstall! +BundleClean +q
