#!/bin/bash

#curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh
ln -s "$(pwd)/./vimrc.local" ~/.vimrc.local
ln -s "$(pwd)/vimrc.bundles.local" ~/.vimrc.bundles.local
ln -s "$(pwd)./vimrc.before.local" ~/.vimrc.before.local

#vim +BundleInstall! +BundleClean +q
